FinalProject/MVC/Controllers/CommentController.cs
using BLL.Interfacies.Entities;
using BLL.Interfacies.Services;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class CommentController : Controller
    {
        //
        // GET: /Comment/

        IPhotoCommentService commentService;

        public CommentController(IPhotoCommentService commentService)
        {
            this.commentService = commentService;
        }

        [Authorize]
        [HttpPost]
        public ActionResult Add(int id, string comment, int last)
        {
            if (!string.IsNullOrWhiteSpace(comment))
            {
                commentService.AddComment(new Comment()
                {
                    Author = User.Identity.Name,
                    Text = comment
                }, id);

                var comments = commentService.GetLastComments(id, last);
                return Json(comments);
            }
            return Json(null);
        }


    }
}

FinalProject/MVC/Controllers/LikeController.cs
using BLL.Interfacies.Services;
using MVC.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class LikeController : Controller
    {
        //
        // GET: /Like/
        
        IPhotoLikeService likeService;
        IPhotoService photoService;

        public LikeController(IPhotoService photoService, IPhotoLikeService likeService)
        {
            this.photoService = photoService;
            this.likeService = likeService;
        }

        [Authorize]
        [HttpPost]
        public ActionResult LikeResolve(int id, Status status)
        {
            if (status == Status.Like)
                return Like(id);
            else if (status == Status.Dislike)
                return Dislike(id);
            return null;
        }


        private ActionResult Like(int id)
        {
            likeService.AddLike(User.Identity.Name, id);
            var likesNumber = likeService.NumberOfLikes(id);

            return Json(likesNumber);
        }


        private ActionResult Dislike(int id)
        {
            likeService.RemoveLike(User.Identity.Name, id);
            var likesNumber = likeService.NumberOfLikes(id);

            return Json(likesNumber);

        }

        [ChildActionOnly]
        public ActionResult LikeButton(bool status)
        {
            return PartialView(status);
        }
    }
}

FinalProject/MVC/Controllers/PhotoController.cs
using BLL.Interfacies.Services;
using MVC.Infrastructure;
using MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class PhotoController : Controller
    {
        //
        // GET: /Photo/

        IPhotoLikeService likeService;
        IPhotoService photoService;
        IPhotoCommentService commentService;


        public PhotoController(IPhotoService photoService, IPhotoLikeService likeService, IPhotoCommentService commentService)
        {
            this.photoService = photoService;
            this.likeService = likeService;
            this.commentService = commentService;
        }

        [Authorize]
        [HttpGet]
        public ActionResult AddPhoto()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddPhoto(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return RedirectToAction("FileNotSelected", "Error");
            }
            var photo = photoService.AddPhoto(new PhotoSaver(file, Server.MapPath(WebConfigurationManager.AppSettings["StoragePath"])), User.Identity.Name);
            return View("Edit",new PhotoEditModel() { Id = photo.Id, PhotoUrl = photo.ResolveLink().PhotoLink });
        }
        
        [Authorize]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var photo = photoService.GetPhoto(id);
            if (photo == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            if (!string.Equals(photo.UserName, User.Identity.Name, StringComparison.InvariantCultureIgnoreCase))
            {
                return RedirectToAction("WrongPermission", "Error");
            }
            return View(new PhotoEditModel() { Id = photo.Id, PhotoUrl = photo.ResolveLink().PhotoLink});
        }

        [Authorize]
        [HttpPost]
        public ActionResult Edit(PhotoEditModel model)
        {
            var photo = photoService.GetPhoto(model.Id);
            if (photo == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            if (!string.Equals(photo.UserName, User.Identity.Name, StringComparison.InvariantCultureIgnoreCase))
            {
                return RedirectToAction("WrongPermission", "Error");
            }
            photoService.EditDescription(model.Id, model.Title);
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Details(int id)
        {
            var photo = photoService.GetPhoto(id);

            if (photo == null)
                return RedirectToAction("NotFound", "Error");

            photo.ResolveLink();

            return View(new PhotoModel() { Id = photo.Id,
                UserName = photo.UserName,
                CreatedDateTime = photo.CreatedDateTime,
                PhotoLink = photo.PhotoLink,
                LikesNumber = photo.LikesNumber,
                Title = photo.Title,
                Like = User.Identity.IsAuthenticated ? likeService.VerifyLikeAbility(User.Identity.Name, id) : false,
                Comments = commentService.GetCommentsByPhoto(id)
            });   
        }

        public ActionResult Page(int page)
        {
            ViewBag.Page = page;
            return View(page);
        }

        [ChildActionOnly]
        public ActionResult PhotoPage(int page)
        {
            int requestSize;
            int photosOnPage = int.Parse(WebConfigurationManager.AppSettings["PhotosOnPage"]);
            var photos = photoService.GetPhotos(photosOnPage, page, out requestSize);

            var model = new PhotoPageModel()
            {
                Photos = photos.Select(x => x.ResolveLink()),
                PageStatus = new PageStatus { PageNumber = page, PageLast = requestSize - (page * photosOnPage) <= 0 },
                DefaultDestination = new ActionDestination(){Action = "Page", Controller = "Photo"}
            };

            return PartialView("_PhotoPage", model);
        }

    }
}

FinalProject/MVC/Views/Photo/AddPhoto.cshtml
@{
    ViewBag.Title = "AddPhoto";
}

<h2>AddPhoto</h2>

@using (Html.BeginForm("AddPhoto", "Photo", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" accept="image/*" />
    <input type="submit" value="OK" />
}

FinalProject/MVC/Views/Photo/Details.cshtml
@model MVC.Models.PhotoModel

@{
    ViewBag.Title = Model.Title;
}


<fieldset>


    <div class="img-container">
        <img class="full" src=@Url.Content(@Model.PhotoLink) alt=""><p></p>
    </div>


    <div class="row image-description">
        <div class="col-md-8">
            @Html.DisplayFor(model => model.Title)
            <br />
            @if (Model.UserName == User.Identity.Name)
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
            }
            else
            {
                @Html.ActionLink(Model.UserName, "User", "User", new { user = Model.UserName }, null)
            }
        </div>
        <div class="col-md-4">
            <div style="float: right; display: inline-block">
                @if (HttpContext.Current.User.Identity.IsAuthenticated)
                {
                    <div>

                        @using (Ajax.BeginForm("LikeResolve", "Like", new AjaxOptions()
                         {
                             UpdateTargetId = "likes",
                             InsertionMode = InsertionMode.Replace,
                             OnBegin = string.Format("pressLike({0})", @Model.Id)
                         }))
                        {

                            <input type="hidden" name="id" value=@Model.Id />
                            <input id=@Model.Id type="hidden" name="status" value=@((Model.Like ? MVC.Helpers.Status.Dislike : MVC.Helpers.Status.Like).ToString().ToLower()) />
                            @MVC.Helpers.LikeButtonHelper.LikeButton(Html, Model.Like, Model.Id)
                        }

                    </div>
                }
            </div>
            <div style="float: right; margin-right: 10px">
                @Html.DisplayFor(model => model.CreatedDateTime)
                <div>
                    <span>Like</span>
                    <span id="likes" class="display-field">
                        @Html.DisplayFor(model => model.LikesNumber)
                    </span>
                </div>
            </div>
        </div>
    </div>

    <div id="comment-result">
        @Html.Partial("CommentsList", Model.Comments)
    </div>

    @if (HttpContext.Current.User.Identity.IsAuthenticated)
    {
        <div>
            @using (Ajax.BeginForm("Add", "Comment", new AjaxOptions()
            {
                UpdateTargetId = "",
                InsertionMode = InsertionMode.InsertAfter,
                OnSuccess = "OnLoadComment"

            }))
            {
                <input id="last" type="hidden" name="last" value="@(Model.Comments != null ? Model.Comments.Count() : 0)" />

                <input type="hidden" name="id" value=@Model.Id />
                <textarea class="full-input" name="comment" id="comments" required></textarea>
                <input type="submit" value="Send" />
            }
        </div>
    }




</fieldset>



@section scripts{ @Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/Comments")
}
@section headscripts{ @Scripts.Render("~/bundles/Likes")}

FinalProject/MVC/Views/Photo/Edit.cshtml
@model MVC.Models.PhotoEditModel

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm("Edit", "Photo", FormMethod.Post, null))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <div>
            <img class="full" src=@Url.Content(@Model.PhotoUrl) alt=""><p></p>
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title, new { @class = "full-input"})
            @Html.ValidationMessageFor(model => model.Title)

        </div>
        <input type="hidden" name="id" value="@Model.Id" />
        <p>
            <input type="submit" value="Save" />
        </p>

    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FinalProject/MVC/Views/Photo/Page.cshtml

@{
    ViewBag.Title = "Page " + ViewBag.Page;
}

@Html.Action("PhotoPage", "Photo", new { page = ViewBag.Page })

FinalProject/MVC/Views/Photo/_PhotoPage.cshtml
@model MVC.Models.PhotoPageModel

<div class="section">
    <div class="container">
        <div class="row">


            @foreach (var group in Model.Photos.Select((e, i) => new { Item = e, Grouping = (i / 3) }).GroupBy(e => e.Grouping))
            {
                <div class="row">
                    @foreach (var photo in group)
                    {
                        <div class="col-md-4">
                            <div class="well" align="center">
                                <a href=@Url.Action("Details", "Photo", new { id = photo.Item.Id })>
                                    <img class="thumbnail img-responsive preview" src=@Url.Content(@photo.Item.PhotoLink) />
                                </a>
                            </div>

                        </div>
                    }
                </div>
            }

        </div>
        <div>
            @if (!Model.PageStatus.PageFirst)
            {
                <div class="previous">
                    @Html.ActionLink("Previous", "Page", "Photo", new { page = Model.PageStatus.PageNumber - 1 }, new { @class = "btn btn-default" })
                </div>
            }
            @if (!Model.PageStatus.PageLast)
            {
                <div class="next">
                    @Html.ActionLink("Next", "Page", "Photo", new { page = Model.PageStatus.PageNumber + 1 }, new { @class = "btn btn-default" })
                </div>
            }

        </div>
    </div>
</div>